Fix/time out argument
Dekker1/minizinc-slurm pull request #39
Opened 2023-10-16 06:55 UTC by hbierlee

2023-10-16 07:27 UTC, Dekker1 commented
It seems this supersedes #37 and #38

2023-10-17 01:38 UTC, hbierlee commented
Yes, I accidentally didn't make the PR's independant (although I explicilty tried to do this). Shall I force-push fix this?

2023-10-17 05:04 UTC, Dekker1 requested changes
Could you have a quick look at the comments. Once they're resolved (probably ignore the `Enum` one), then I think this can be merged

2023-10-17 05:04 UTC, Dekker1 commented on pyproject.toml
> -pytest = "^7.4.0"
I don't understand why it is no longer in the `dev` dependencies. We now have testing for the package right, so it probably belongs here still

2023-10-17 05:04 UTC, Dekker1 commented on src/mzn_bench/analysis/report_status.py
> +from typing import Iterable, Optional
Was `Optional` already used somewhere? I don't see it in the changes lines

2023-10-17 05:04 UTC, Dekker1 commented on src/mzn_bench/analysis/report_status.py
> +    keys: Iterable[str], statistics: Path, avg: str, tablefmt: str
I would lean to a `Enum` type argument, but I suppose with this package `str` is probably fine

2023-10-18 01:08 UTC, hbierlee commented
Processed requested changes!

2023-10-20 04:01 UTC, Dekker1 approved these changes

2023-10-20 04:02 UTC, merged